version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: ./frontend/
    container_name: bshare_application
    profiles: ["dev", "dev-frontend"]
    ports:
      - 3000:80
    volumes:
      - ./frontend/:/var/www/
      - ./frontend/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./frontend/config/start-apache:/usr/local/bin/start-apache
    environment:
      Webservice_HOST: bshare_backend
      APP_ENV: development
      APACHE_RUN_USER: apache-www-volume
      APACHE_RUN_GROUP: apache-www-volume
      APP_KEY: SomeRandomStringToAddSecurity123

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: ./server/
    container_name: bshare_backend
    ports:
      - 3100:3100
      - 9229:9229
    volumes:
      - ./server/:/app
    profiles: ["dev", "dev-backend"]
    working_dir: /app
    depends_on:
      - mysql
    command: yarn dev
    environment:
      HOST: 127.0.0.1:3100
      ORM_CONNECTION: mysql
      ORM_HOST: bshare_database_test
      ORM_USERNAME: root
      ORM_PASSWORD: bshare
      ORM_DATABASE: db_bshare

  mysql:
    image: mysql:8.0
    container_name: bshare_database_test
    profiles: ["dev", "dev-backend", "deploy"]
    ports:
      - 3309:3306
    volumes:
      - bshare_database_test:/var/lib/mysql
    environment:
      MYSQL_USER: CANELA
      MYSQL_PASSWORD: canela
      MYSQL_ROOT_PASSWORD: bshare
      MYSQL_DATABASE: db_bshare

volumes:
  bshare_database_test:
