version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: bshare_backend
    ports:
      - 80:3100
    volumes:
      - ./src/:/var/www/html
    profiles: ["dev", "dev-backend"]
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: bshare_database_test
      MYSQL_USER: root
      MYSQL_PASSWORD: bshare
      MYSQL_DB: db_bshare

  mysql:
    image: mysql:8.0
    container_name: bshare_database_test
    profiles: ["dev", "dev-backend", "deploy"]
    ports:
      - 3309:3306
    volumes:
      - bshare_database_test:/var/lib/mysql
    environment:
      MYSQL_USER: CANELA
      MYSQL_PASSWORD: canela
      MYSQL_ROOT_PASSWORD: bshare
      MYSQL_DATABASE: db_bshare

volumes:
  bshare_database_test:
