#!/usr/bin/env bash

sed -i 's,^upload_max_filesize = .*$, upload_max_filesize = 2G,' /usr/local/etc/php/php.ini
sed -i 's,^memory_limit = .*$, memory_limit = 40G,' /usr/local/etc/php/php.ini
sed -i 's,^post_max_size = .*$, post_max_size = 3G,' /usr/local/etc/php/php.ini